name: hsicompressai
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.1.1
  - packaging=24.1
  - python=3.12.2
  - pip:
      - python-box
      - einops==0.8.1
      - hydra-colorlog==1.2.0
      - hydra-core==1.4.0.dev1
      - hydra-optuna-sweeper==1.2.0
      - optuna==2.10.1
      - pytorch-lightning==2.5.0.post0
      - pytorch-msssim==1.0.0
      - rasterio==1.4.3
      - rich==13.5.2
      - rootutils==1.0.7
      - scipy==1.15.2
      - segmentation-models-pytorch==0.4.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - torch-summary==1.4.5
      - torchgeo==0.6.2
      - torchmetrics==1.6.2
      - torchvision==0.21.0
      - transformers==4.49.0
      - triton==3.2.0
      - wandb==0.19.8
      - compressai==1.2.6 
      - mamba-ssm==2.2.4
      - causal-conv1d>=1.4.0
