_target_: hsicompressai.models.hsn11_module.HSN11LitModule

net:
  _target_: hsicompressai.models.neural.srcmodel.ScalableReduceComplexityEntropyModel
  src_channels: 202
  cluster_size: 3
  N: 192
  M: 192
  loss_metric: "mse"
  loss_return: "all"
  target_bpppc: 0.1

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: Null
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

criterion: Null

state_dict: Null

# compile model for faster training with pytorch 2.0
compile: false

