_target_: hsicompressai.models.hsn11_module.HSN11LitModule

net:
  _target_: hsicompressai.models.neural.cae3d.SpectralSignalsCompressorNetwork
  src_channels: 202
  target_compression_ratio: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: Null
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

criterion:
  _target_: torch.nn.MSELoss

state_dict: Null

# frozen: False

# compile model for faster training with pytorch 2.0
compile: false

